### ISSUE TITLE
Should this be using CDT Dependencies?

### ISSUE THREAD

**Issue by paxsonsa** [conda-forge/glew-feedstock#9]
Hey there,

I was look at this recipe and it appears that it relies on OpenGL being installed on the local machine. Do we think this should be more isolated and use the cdt functionality available?

Cheers!

**Comment by scopatz** [comment]
The basic heirarchy for dependencies is, in order of preference is,

* Make or use a conda-forge package for the dep
* Use a defaults package for a dep
* Use a CDT for a dep
* Use a yum_requirements for a dep
* Silently require the package to exist

**Comment by paxsonsa** [comment]
I am just getting up to speed on the whole CDTs and conda isolation. @scopatz that is really useful information. 

Let me take a stab at an example and hopefully @conda-forge/core will be able to validate if I am mixing something up.

**Comment by scopatz** [comment]
Yeah, it should probably be in the docs :)

**Comment by scopatz** [comment]
Added in https://github.com/conda-forge/conda-forge.github.io/pull/690

**Comment by paxsonsa** [comment]
So one one of the major first things for higher isolation is build and relying on libGL which conda-forge does not yet have (or I can't find it)

I did a test on my end with Centos7/6 to see what I would need to do to build with mostly cdts and a cmake toolchain file. I am not sure if that is the best approach and frankly, I still don't understand the the way CDTs operate with a package. One way I got it building for linux was like so:

meta.yaml
``` yaml
{% set name = "glew" %}
{% set version = "2.0.0" %}
{% set sha256 = "cc88d2f70a185185eb050eb13789f498425fcd58230bfd65da496b8008f046f2" %}
{% set dev_url = "https://github.com/nigels-com/glew" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: {{ dev_url }}/releases/download/{{ name }}-{{ version }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - pkg-config                         # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libXfixes') }}             # [linux]
    - {{ cdt('libXxf86vm') }}            # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libXdamage') }}            # [linux]
    - {{ cdt('libXau') }}                # [linux]

  run:
    - {{ cdt('libx11') }}                # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libXfixes') }}             # [linux]
    - {{ cdt('libXxf86vm') }}            # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxrender') }}            # [linux]
    - {{ cdt('mesa-libgl') }}            # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libXdamage') }}            # [linux]
    - {{ cdt('libXau') }}                # [linux]

test:
  requires:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
  commands:
    - test -f $PREFIX/include/GL/glew.h  # [unix]
```

Then adding a cmake file like so:
linux.cmake
```
# this one is important
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_PLATFORM Linux)
#this one not so much
# set(CMAKE_SYSTEM_VERSION 1)

# specify the cross compiler
set(CMAKE_C_COMPILER $ENV{CC})

# where is the target environment
set(CMAKE_FIND_ROOT_PATH "$ENV{PREFIX}" "$ENV{BUILD}/$ENV{HOST}/sysroot" "$ENV{BUILD_PREFIX}/$ENV{HOST}/sysroot")

# search for programs in the build host directories
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

Then the build scripts cmake call contains this:
```
cmake -DCMAKE_INSTALL_PREFIX:PATH="${PREFIX}" \
      -DCMAKE_INSTALL_LIBDIR="lib" \
      -DCMAKE_TOOLCHAIN_FILE="${RECIPE_DIR}/linux.cmake" \
      ./cmake
```


I am not sure if this is even what we need as when the run installation it all the libGL libs are installed in the sys root of the environment and I am not sure how that is used. 

Hopefully someone can enlighten this/us. I also think this avoids using conda-forge packages which it should probably NOT do.
